name: Build Fedora bootc-k3s-agent image
on:
  workflow_dispatch:
  push:
    paths:
      - bootc/fedora/Containerfile
      - bootc/common/kubevirt/**
      - bootc/common/k3s/**
    branches:
      - main

jobs:
  build_bootc:
    uses: ./.github/workflows/build-rhel-bootc.yml
    with:
      image_name: fedora-bootc-k3s-agent
      archs: x86_64, arm64
      build-args: |
        K3S_AGENT=true
        LONGHORN=true
      containerfiles: |
        bootc/fedora/Containerfile
        bootc/common/kubevirt/Containerfile
        bootc/common/k3s/Containerfile
    permissions:
      contents: read
      packages: write
    secrets: inherit
